import { BANNER_HEIGHT, BANNER_WIDTH } from "@/types/banner";

/** Defaults mirrored in `overlayBrandElements` for draggable hit areas. */
export const LAYOUT_MARGIN = 20;
export const LAYOUT_LOGO_TOP = LAYOUT_MARGIN;
export const LAYOUT_CONTENT_START_X = Math.round(BANNER_WIDTH * 0.3) + 24;
export const LAYOUT_TITLE_Y = Math.round(BANNER_HEIGHT * 0.46);
export const LAYOUT_SECONDARY_LOGO_TOP = 24;
export const LAYOUT_SECONDARY_LOGO_RIGHT_PAD = 26;
export const LAYOUT_PRIMARY_LOGO_BOX = 88;
export const LAYOUT_SECONDARY_LOGO_BOX = 72;
export const LAYOUT_SECONDARY_LOGO_LEFT = BANNER_WIDTH - LAYOUT_SECONDARY_LOGO_BOX - LAYOUT_SECONDARY_LOGO_RIGHT_PAD;
export const LAYOUT_TEXT_BLOCK_WIDTH_RATIO = 0.52;
export const LAYOUT_PHONE_REGION_W = 300;
export const LAYOUT_PHONE_REGION_H = 64;
export const LAYOUT_PHONE_REGION_LEFT = BANNER_WIDTH - LAYOUT_PHONE_REGION_W - 12;
export const LAYOUT_PHONE_REGION_TOP = BANNER_HEIGHT - LAYOUT_PHONE_REGION_H - 8;
export const LAYOUT_TEXT_BLOCK_LEFT = LAYOUT_CONTENT_START_X;
export const LAYOUT_TEXT_BLOCK_TOP = Math.round(LAYOUT_TITLE_Y - 44);
export const LAYOUT_TEXT_BLOCK_WIDTH = Math.round(BANNER_WIDTH * LAYOUT_TEXT_BLOCK_WIDTH_RATIO);
export const LAYOUT_TEXT_BLOCK_HEIGHT = Math.round(BANNER_HEIGHT * 0.44);
